application: nyc-restaurants2
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
- url: /css
  static_dir: static/css
  http_headers:
    Vary: Accept-Encoding
- url: /js
  static_dir: static/js
  http_headers:
    Vary: Accept-Encoding
- url: /admin/.*
  script: main.app
  login: admin
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
